I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 77, in script call
    call fight_start(girl,rat)
  File "game/battle.rpy", line 34, in script call
    call fight_step(player, enemy)
  File "game/battle.rpy", line 55, in script call
    call fight_loop(player,enemy)
  File "game/script.rpy", line 77, in script call
    call fight_start(girl,rat)
  File "game/battle.rpy", line 34, in script call
    call fight_step(player, enemy)
  File "game/battle.rpy", line 55, in script call
    call fight_loop(player,enemy)
ScriptError: could not find label 'fight_loop'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 77, in script call
    call fight_start(girl,rat)
  File "game/battle.rpy", line 34, in script call
    call fight_step(player, enemy)
  File "game/battle.rpy", line 55, in script call
    call fight_loop(player,enemy)
  File "C:\2022portable_programs\renpy-8.2.3-sdk\renpy\ast.py", line 1416, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 77, in script call
    call fight_start(girl,rat)
  File "game/battle.rpy", line 34, in script call
    call fight_step(player, enemy)
  File "game/battle.rpy", line 55, in script call
    call fight_loop(player,enemy)
  File "C:\2022portable_programs\renpy-8.2.3-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'fight_loop'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
SpringQuinox 1.0
Sun Sep  8 06:12:52 2024
